#!python
import argparse
import json
import os

from mozdeploy import build

REQUIRED_VALS = ['hostroot', 'command', 'build_dir', 'app']


def error(msg):
    print msg
    exit(1)


manifest = os.path.join(os.getcwd(), 'mozdeploy.json')

if not os.path.isfile(manifest):
    error("%s does not exist" % manifest)

try:
    config = json.load(open(manifest))
except ValueError:
    error("%s is not valid JSON" % manifest)

pkg_config = {}
for v in REQUIRED_VALS:
    try:
        pkg_config[v] = config[v]
    except KeyError:
        error("%s does not contain key: %s" % (manifest, v))

parser = argparse.ArgumentParser()

parser.add_argument('-v', '--version', help="Version to build", required=True)
args = parser.parse_args()
pkg_config['version'] = args.version
build.package_app(**pkg_config)
