#!python
import argparse

from mozdeploy import build


parser = argparse.ArgumentParser()
parser.add_argument('--hostroot', required=True)
parser.add_argument('--command', required=True)
parser.add_argument('--version', required=True)
parser.add_argument('--build_dir', required=True)
parser.add_argument('--app', required=True)

args = parser.parse_args()

build.package_app(**vars(args))
