#!python

import argparse

from mozdeploy import deploy


parser = argparse.ArgumentParser()
parser.add_argument('--pkgroot', required=True)
parser.add_argument('--app_dir', required=True)
parser.add_argument('--app', required=True)
parser.add_argument('--build_id', default='LATEST')

args = parser.parse_args()

deploy.install_app(**vars(args))
